# Generated by Django 6.0.6 on 2026-07-17 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area_of_expertise',
        ),
    ]
