# Generated by Django 6.0.6 on 2026-07-09 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_title', models.CharField(max_length=255)),
                ('arabic_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('english_description', models.TextField()),
                ('arabic_description', models.TextField()),
                ('image', models.ImageField(upload_to='contents/')),
                ('fake_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('real_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('show_in_home', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='category.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_title', models.CharField(max_length=255)),
                ('arabic_title', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='lessons/')),
                ('file', models.FileField(upload_to='lessons/files/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.content')),
            ],
        ),
    ]
